### ISSUE TITLE
'Bloom' could not be found

### ISSUE THREAD

**Issue by dmitrykolesnikovich** [GarrettGunnell/Disney-PBR#1]
`Assets\Scripts\SimpleCameraController.cs(13,17): error CS0246: The type or namespace name 'Bloom' could not be found (are you missing a using directive or an assembly reference?)`

![image](https://github.com/GarrettGunnell/Disney-PBR/assets/6131040/3a886868-39b9-47b3-a673-cf9610b06f6d)

**Comment by GarrettGunnell** [comment]
This has nothing to do with the actual shader it's just an error cause my bloom script is not present in the repo, you can remove the camera controller from the camera.
